'use strict';
const express=require('express');const {authenticateToken,requireRole}=require('../middleware/auth');const {assembleEvidenceWorkflow}=require('../domain/evidencePolicy');const router=express.Router();
const tenant=(req,res,next)=>{req.tenantId=req.user?.tenantId||req.user?.tenant_id;if(!req.tenantId)return res.status(403).json({error:'Tenant claim required'});next();};
router.use(authenticateToken,tenant);
router.get('/',requireRole('researcher','scientist','clinical_reviewer','admin'),async(req,res)=>{const result=await req.app.get('db').query('SELECT * FROM evidence_workflows WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 100',[req.tenantId]);res.json(result.rows);});
router.post('/',requireRole('researcher','scientist','admin'),async(req,res)=>{
 const key=req.get('Idempotency-Key');if(!key||key.length>128)return res.status(400).json({error:'Valid Idempotency-Key required'});const assessment=assembleEvidenceWorkflow(req.body||{});const status=assessment.valid?'assembled':'failed';const pool=req.app.get('db');const client=await pool.connect();
 try{await client.query('BEGIN');const prior=await client.query('SELECT * FROM evidence_workflows WHERE tenant_id=$1 AND idempotency_key=$2 FOR UPDATE',[req.tenantId,key]);if(prior.rows[0]){await client.query('COMMIT');return res.json(prior.rows[0]);}
 const result=await client.query(`INSERT INTO evidence_workflows(tenant_id,idempotency_key,status,input,assessment,failure_code,created_by)VALUES($1,$2,$3,$4,$5,$6,$7)RETURNING *`,[req.tenantId,key,status,req.body,assessment,assessment.valid?null:'evidence_validation_failed',String(req.user.id)]);
 await client.query('INSERT INTO evidence_workflow_audit(workflow_id,tenant_id,actor_id,action,details)VALUES($1,$2,$3,$4,$5)',[result.rows[0].id,req.tenantId,String(req.user.id),status,{violations:assessment.violations}]);await client.query('COMMIT');res.status(201).json(result.rows[0]);
 }catch(_){await client.query('ROLLBACK');res.status(500).json({error:'Evidence workflow persistence failed',code:'workflow_persistence_failed'});}finally{client.release();}
});
router.post('/:id/submit',requireRole('researcher','scientist','admin'),async(req,res)=>{const pool=req.app.get('db');const result=await pool.query(`UPDATE evidence_workflows SET status='pending_professional_review',updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND status='assembled' RETURNING *`,[req.params.id,req.tenantId]);if(!result.rows[0])return res.status(409).json({error:'Only assembled evidence can be submitted'});await pool.query('INSERT INTO evidence_workflow_audit(workflow_id,tenant_id,actor_id,action)VALUES($1,$2,$3,$4)',[req.params.id,req.tenantId,String(req.user.id),'submitted']);res.json(result.rows[0]);});
router.post('/:id/review',requireRole('clinical_reviewer','admin'),async(req,res)=>{
 if(!['accept_for_research','reject'].includes(req.body?.decision)||!String(req.body?.rationale||'').trim()||!req.body?.credentialReference||req.body?.attestation!==true)return res.status(400).json({error:'decision, rationale, credentialReference and attestation=true required'});
 const status=req.body.decision==='accept_for_research'?'reviewed_for_research':'rejected';const pool=req.app.get('db');const result=await pool.query(`UPDATE evidence_workflows SET status=$1,reviewed_by=$2,review_rationale=$3,credential_reference=$4,updated_at=NOW() WHERE id=$5 AND tenant_id=$6 AND status='pending_professional_review' AND created_by<>$2 RETURNING *`,[status,String(req.user.id),req.body.rationale.trim(),req.body.credentialReference,req.params.id,req.tenantId]);if(!result.rows[0])return res.status(409).json({error:'Pending workflow and independent professional reviewer required'});await pool.query('INSERT INTO evidence_workflow_audit(workflow_id,tenant_id,actor_id,action,details)VALUES($1,$2,$3,$4,$5)',[req.params.id,req.tenantId,String(req.user.id),status,{rationale:req.body.rationale,credentialReference:req.body.credentialReference}]);res.json(result.rows[0]);
});
module.exports=router;
